spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: jdbc:mysql://172.16.159.20:3306/qq?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
          username: root
          password: 158262751
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          username: root
          password: 158262751
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.16.159.21:3306/xuweizhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        slave_2:
          username: root
          password: 158262751
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.16.159.22:3306/xuweizhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.data.dynamic.model
  mapper-locations: classpath:com/data/dynamic/mapper/*.xml
