spring:
  #  支持（content-type=application/json）请求中格式为 yyyy-MM-dd HH:mm:ss的字符串，后台用@RequestBody接收，
  #  及返回值date转为yyyy-MM-dd HH:mm:ss格式string；
  #  不支持（content-type=application/json）请求中yyyy-MM-dd等类型的字符串转为date；
  #  不支持java8日期api;
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: home

mybatis-plus:
  global-config:
    db-config:
#      id-type: assign_id
#      capital-mode: true
      # 全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-field: flag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.java.prepare.model
  mapper-locations: classpath:com/java/prepare/mapper/*.xml

#logging:
#  level:
#    com.java.prepare: debug
logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
---
spring:
  profiles: company
  datasource:
#    url: jdbc:mysql://172.16.142.128:3306/prepare?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:p6spy:mysql://172.16.142.128:3306/prepare?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  # https://github.com/redisson/redisson/wiki
  redis:
    port: 6379
    timeout: 10000ms #连接时间
    host: 172.16.142.128
  data:
    mongodb:
      #     uri: mongodb://192.192.192.64:27017,192.192.192.64:27018,192.192.192.64:27019/test?replicaSet=mongorepl0&readPreference=secondaryPreferred&appname=${spring.application.name}&ssl=false&w=majority&readConcern=majority
      uri: mongodb://172.16.142.128:27017/test
---
spring:
  profiles: home
  datasource:
#    url: jdbc:mysql://192.168.208.128:3306/prepare?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:p6spy:mysql://192.168.208.128:3306/prepare?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  redis:
    port: 6379
    timeout: 10000ms #连接时间
    host: 192.168.208.128
  data:
    mongodb:
#     uri: mongodb://192.192.192.64:27017,192.192.192.64:27018,192.192.192.64:27019/test?replicaSet=mongorepl0&readPreference=secondaryPreferred&appname=${spring.application.name}&ssl=false&w=majority&readConcern=majority
     uri: mongodb://192.168.208.128:27017/test
