spring:
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms #连接池等待时间
    host: ${linux.port.base}
    port: 6379
    timeout: 1000ms #连接时间
  cache:
    cache-names: menus_cache
    redis:
      time-to-live: 1800s
  mail:
    host: smtp.qq.com
    port: 465
    username: 1510161612@qq.com
    password: fhmvfkwxjwmzhhjd
    default-encoding: UTF-8
    properties:
        mail:
          smtp:
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
          debug: true