linux:
  port:
    base: 47.105.218.58                 # Linux 主服务器端口
    master:
      mysql: ${linux.port.base}:3306    # Linux 主 Mysql 端口 写
    slave:
      slave1: ${linux.port.base}:3306   # Linux 从 Mysql 端口 读
      slave2: ${linux.port.base}:3306   # Linux 从 Mysql 端口 读

spring:
  profiles:
    active: boot # 激活配置文件
    #    include: boot,druid1 或者 ProtertyConfigure 类中激活配置文件
    include: hikari,redis # 或者 ProtertyConfigure 类中激活配置文件 druid3 配置无效，数据源有效
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    readSize: 2 # 从数据库个数
  main:
    allow-bean-definition-overriding: true
  #  elasticsearch:
  #    jest:
  #      uris: 127.0.01:9200
  data:
    elasticsearch:
      cluster-name: myapp   #默认为默认为elasticsearch
#      cluster-nodes: ${linux.port.base}:9300,${linux.port.base}:9301,${linux.port.base}:9302 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      cluster-nodes: ${linux.port.base}:9300 # 人穷啊，开不起4G云服务,${linux.port.base}:9301,${linux.port.base}:9302 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
#      properties:
#        enable: true #是否开启本地存储
#        path:
#          logs: ./elasticsearch/log #elasticsearch日志存储目录
#          data: ./elasticsearch/data #elasticsearch数据存储目录

com:
  xwz:
    sample: 我们
    # 直接引用属性值
    desc: ${com.xwz.sample}
    # 使用随机数
    value: ${random.value}
