# 这个必须放在这个里面吗？
#redisson:
#  address: redis://47.105.218.58:6379
server:
  port: 11111
spring:
  #  jackson:
  #    time-zone: GMT+8
  profiles:
    active: hikari
#  redis:
#    port: 6379
#    timeout: 10000ms #连接时间
#    host: 47.105.218.58
#    database:
#    password:
#    ssl:
#    cluster:
#      nodes:
#    sentinel:
#      master:
#      nodes:
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB

# 日志打印
#logging:
#  level:
#    com.spring.demo.mapper: debug
#    io.swagger.models.parameters.AbstractSerializableParameter: error
#  datasource:
#    url: jdbc:mysql://192.192.192.61:6100/dftc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

#http配置服务
#最大连接数
#http:
#  maxTotal: 100
#  #并发数
#  defaultMaxPerRoute: 20
#  #创建连接的最长时间
#  connectTimeout: 1000
#  #从连接池中获取到连接的最长时间
#  connectionRequestTimeout: 500
#  #数据传输的最长时间
#  socketTimeout: 10000
#  #提交请求前测试连接是否可用
#  staleConnectionCheckEnabled: true
#sync:
#  pool:
#    core-size: 10
#    await-time: 60
#    alive-time: 200
#    queue-capacity: 25
#    max-size: 20
#
### 百度图片识别
#baidu:
#  picture:
#    client:
#      appId: 17289319
#      appKey: A5AEehVP2mlVTxwN8VV7rXhX
#      secretKey: b7SU0Q6pIGZfli22Yni4Nh9metjLLNm3
