# 我们配置了三个数据，其中第一个作为默认数据源也就是我们的master数据源。主要是写操作，那么读操作交给我们的slave1跟slave2
spring:
  datasource:
    #    url: jdbc:mysql://47.105.218.58:3306/qq?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://47.105.218.58:3306/qq?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 158262751
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    timeout: 10000ms #连接时间
    host: 47.105.218.58
#    database:
#    password:
#    ssl:
#    cluster:
#      nodes:
#    sentinel:
#      master:
#      nodes:
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB

# redisson lock
redisson:
  address: redis://47.105.218.58:6379
#  password:
#  master-name: mymaster
#  password: xxxx
#  redisson:
#    sentinel-addresses: 10.47.91.83:26379,10.47.91.83:26380,10.47.91.83:26381


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.spring.demo.model
  mapper-locations: classpath:com/spring/demo/mapper/*.xml

logging:
  level:
    com.spring.demo.mapper: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error

# httpClient 连接池配置
http:
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true

# 异步线程池配置文件
sync:
  pool:
    core-size: 10
    await-time: 60
    alive-time: 200
    queue-capacity: 25
    max-size: 20

# 百度图片识别
baidu:
  picture:
    client:
      appId: 17289319
      appKey: A5AEehVP2mlVTxwN8VV7rXhX
      secretKey: b7SU0Q6pIGZfli22Yni4Nh9metjLLNm3