spring:
  application:
    name: redis
#  profiles:
#    active: local
  redis:
    port: 6379
    timeout: 10000 #连接时间
    host: localhost
    database: 0
    password:
    redisson:
      # 配置单点模式
      config: classpath:redisson-single-dev.yml
#logging:
#  config: classpath:logbacks-spring.xml
#  logstash:
#    host: 192.168.20.130:5000
