# 服务配置
server:
  port: 8000

# spring 配置
spring:
  application:
    name: elasticsearch
  output:
    ansi:
      enabled: always
#logging:
#  level:
#    org.springframework.data.elasticsearch: debug
