cluster.name: myapp
node.name: node2
network.bind_host: 0.0.0.0
network.publish_host: 172.31.75.153
http.port: 9201
transport.tcp.port: 9301
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
node.data: true
discovery.zen.ping.unicast.hosts: ["172.31.75.153:9300","172.31.75.153:9301","172.31.75.153:9302"]
discovery.zen.minimum_master_nodes: 2
