spring:
  rabbitmq:
    host: 47.105.218.58
# \u6211\u4EEC\u914D\u7F6E\u4E86\u4E09\u4E2A\u6570\u636E\uFF0C\u5176\u4E2D\u7B2C\u4E00\u4E2A\u4F5C\u4E3A\u9ED8\u8BA4\u6570\u636E\u6E90\u4E5F\u5C31\u662F\u6211\u4EEC\u7684master\u6570\u636E\u6E90\u3002\u4E3B\u8981\u662F\u5199\u64CD\u4F5C\uFF0C\u90A3\u4E48\u8BFB\u64CD\u4F5C\u4EA4\u7ED9\u6211\u4EEC\u7684slave1\u8DDFslave2
  datasource:
    url: jdbc:mysql://47.105.218.58/wtf?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 158262751
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  #\u914D\u7F6E\u5305\u626B\u63CF\u4F4D\u7F6E
  configuration:
    #\u9002\u914D\u9A7C\u5CF0\u547D\u540D\u6CD5
    map-underscore-to-camel-case: true #\u9ED8\u8BA4\u4E3Atrue
  #    interceptors: com.xwz.boot.configure.data.MybatisInterceptor \u5931\u8D25
  type-aliases-package: com.java.rabbit.model
  mapper-locations: classpath:com/java/rabbit/mapper/*.xml
